In [1]:
import numpy as np
import ipft 

In [2]:
initialBelief = np.array([
            [9.3953], 
            [9.8427], 
            [10.1268],
            [9.6946], 
            [9.2815], 
            [10.4726],
            [10.7598],
            [3.0242], 
            [10.6167],
            [10.2247],
            [9.0881], 
            [11.5099],
            [9.6757], 
            [9.6167], 
            [8.9347], 
            [10.1384],
            [9.6376], 
            [9.6736], 
            [10.7702],
            [9.7005]])

solver = ipft.PyIpftCld(initialBelief)

In [3]:
print(solver)

In [4]:
solver.search()

(array([-3.]), -22.28993308818901, array([-63.03805753,  40.74812444]))

In [ ]:
solver.reset()
solver.search()

In [5]:
root = solver.getSearchTree()

In [14]:
for n in root.children_[0].children_[5].children_:
    print(n)

In [31]:
for n in root.children_[0].children_[5].children_[3].children_:
    print(n.observation_)
    print(n.count_)
    print(n.values_)

[4.74385583]
7
[-88.28808236 182.16570637]
[7.39182106]
3
[-34.41963593  33.26142894]
[6.76874294]
5
[-79.47816819  38.12830943]
[3.17604309]
7
[-86.58387279  31.65740859]
[8.28911026]
6
[-63.71173072  14.70175542]
[8.72549435]
5
[-87.42812364  23.56857549]


In [52]:
for n in root.children_[0].children_[5].children_[3].children_[0].children_:
    print(n.action_)
    print(n.count_)
    print(n.values_)

[-3.]
1
[-85.1605      22.90655413]
[-1.]
1
[-81.902475    32.53897689]
[0.]
2
[-90.42556325 569.69521242]
[1.]
1
[-92.2         9.9331022]
[3.]
1
[-96.          23.45204318]


In [53]:
for n in root.children_[0].children_[5].children_[3].children_[0].children_[2].children_: # vnodes
    print(n.observation_)
    print(n.belief_.particles_)

[25.86880307]
[[1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]
 [1.32188868]]
[5.03147673]
[[7.68284388]
 [7.4948237 ]
 [7.40262207]
 [7.31701328]
 [7.07928532]
 [7.10804733]
 [6.94756217]
 [7.54449361]
 [7.08905648]
 [7.75791252]
 [7.94821943]
 [7.61176073]
 [7.10804733]
 [7.7012344 ]
 [8.18643271]
 [7.68300645]
 [7.53427989]
 [8.35228696]
 [7.4640428 ]
 [7.09287469]]


In [49]:
root.children_[0].children_[5].children_[3].children_[0].children_[2].children_[0].

0L

In [25]:
root.children_

In [8]:
L0qN0 = root.children_[2]
L0qN0Vs = root.children_[2].children_


In [17]:
len(L0qN0Vs)

8

In [9]:
root.belief_.particles_

array([[10.7598],
       [10.1384],
       [ 9.6736],
       [10.2247],
       [ 9.6946],
       [10.7702],
       [ 9.8427],
       [ 9.6376],
       [11.5099],
       [ 9.6167],
       [10.6167],
       [ 9.3953],
       [ 9.7005],
       [ 9.2815],
       [10.4726],
       [ 3.0242],
       [ 9.0881],
       [ 8.9347],
       [ 9.6757],
       [10.1268]])

In [10]:
for v in L0qN0Vs:
    print(v.belief_.particles_)

[[ 8.9392801 ]
 [10.51684665]
 [10.51684665]
 [ 9.69108638]
 [10.95715274]
 [11.49454437]
 [ 9.55271683]
 [ 9.67094521]
 [10.56126957]
 [10.19935356]
 [ 9.69108638]
 [ 9.63089615]
 [10.22534256]
 [ 9.52403414]
 [ 9.75276123]
 [10.19935356]
 [ 9.63089615]
 [10.46412032]
 [10.78515561]
 [ 9.81606799]]
[[ 9.79680286]
 [ 9.67483608]
 [10.59444228]
 [10.21751246]
 [10.3607295 ]
 [ 9.58807426]
 [ 9.79680286]
 [10.08772231]
 [ 9.37155729]
 [ 9.82901034]
 [11.03648303]
 [ 9.71998583]
 [10.71409847]
 [10.48017624]
 [ 9.46878609]
 [ 9.82901034]
 [ 9.65238049]
 [ 9.14732957]
 [ 9.62671025]
 [ 8.80133601]]
[[ 9.4899101 ]
 [ 9.5438078 ]
 [ 9.86646852]
 [10.29185909]
 [ 9.13867702]
 [ 9.7613012 ]
 [10.29185909]
 [ 9.60661865]
 [ 9.80065596]
 [10.22745736]
 [ 9.86646852]
 [10.19105659]
 [10.53766309]
 [ 9.56271304]
 [ 9.7613012 ]
 [ 9.64896382]
 [ 9.80065596]
 [ 8.9016447 ]
 [11.3821637 ]
 [10.70680979]]
[[3.01257882]
 [3.01257882]
 [3.01257882]
 [3.01257882]
 [3.01257882]
 [3.01257882]
 [3.01257882]

In [18]:
degVNode = L0qN0Vs[3]
degVNode.belief_.particles_

array([[3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882],
       [3.01257882]])

In [19]:
degVNode.belief_.post_particles_

array([[10.88970548],
       [10.24057294],
       [ 9.646017  ],
       [10.12616953],
       [ 9.81227485],
       [10.70282513],
       [ 9.9058039 ],
       [ 9.54080778],
       [11.39410435],
       [ 9.68374543],
       [10.71044586],
       [ 9.44884388],
       [ 9.80376234],
       [ 9.26153376],
       [10.47786044],
       [ 3.01257882],
       [ 9.14280734],
       [ 9.09080335],
       [ 9.67211648],
       [ 9.95360296]])

In [20]:
degVNode.belief_.post_weights_

array([2.80417239e-09, 4.48897096e-36, 1.15133359e-22, 2.80082806e-54,
       4.09768872e-40, 2.15672639e-12, 8.35460156e-60, 8.31831175e-17,
       3.13006736e-05, 1.71697418e-25, 3.11167828e-12, 2.59118521e-13,
       8.23316330e-39, 8.20560754e-09, 3.39410203e-19, 9.99966020e-01,
       5.12804434e-07, 2.15564568e-06, 1.43741359e-24, 1.01184351e-75])

In [21]:
for v in L0qN0Vs:
    print(v.observation_)

[10.27434248]
[9.65062024]
[9.81728269]
[-0.6478485]
[8.72827618]
[14.92908828]
[14.2445306]
[10.6637181]


In [24]:
for v in L0qN0Vs:
    print(v.count_)

898
941
965
926
873
924
902
789


In [23]:
degVNode.observation_

array([-0.6478485])